export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_RECEIVED = 'SEARCH_USER_RECEIVED';
export const SET_SHOT_TYPE = 'SET_SHOT_TYPE';
export const SET_POSITION_AND_SIDE = 'SET_POSITION_AND_SIDE';
export const SCORE_REQUEST = 'SCORE_REQUEST';
export const SCORE_RECIEVED = 'SCORE_RECIEVED';
