export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST"
export const SEARCH_USER_RECEIVED = "SEARCH_USER_RECEIVED"
export const ADD_SCORE = 'ADD_SCORE'
export const SET_MODAL = 'SET_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
export const SCORE_REQUEST = 'SCORE_REQUEST'
export const SCORE_RECIEVED = 'SCORE_RECIEVED'
