export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_RECEIVED = "SEARCH_USER_RECEIVED";
export const SET_SHOT_TYPE = "SET_SHOT_TYPE";
export const SET_POSITION_AND_SIDE = "SET_POSITION_AND_SIDE";
export const POST_GAME_REQUEST = "POST_GAME_REQUEST";
export const POST_GAME_RECIEVED = "POST_GAME_RECIEVED";
