parser: "babel-eslint"
env:
  browser: false
  commonjs: false
  react-native/react-native: true
  es6: true
extends: "plugin:react-native/all"
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
plugins:
  - react
  - react-native
  - import
  - jsx-a11y
rules:
  react-native/no-color-literals: 0
  no-trailing-spaces: 2
  comma-dangle: 2
  no-console: 1
  constructor-super: 2
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
