export const REQUEST_POST_USER_UPDATE = "REQUEST_POST_USER_UPDATE";
export const RECEIVED_POST_USER_UPDATE = "RECEIVED_POST_USER_UPDATE";
export const GET_USER_RECEIVED = "GET_USER_RECEIVED";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const SET_USER = "SET_USER";
