export const REQUEST_POST_USER_UPDATE = "REQUEST_POST_USER_UPDATE";
export const RECEIVED_POST_USER_UPDATE = "RECEIVED_POST_USER_UPDATE";
export const RECEIVED_GET_USER = "RECEIVED_GET_USER";
export const REQUEST_GET_USER = "REQUEST_GET_USER";
export const SET_USER = "SET_USER";
