export const POST_LOGIN_REQUEST = "POST_LOGIN_REQUEST";
export const POST_LOGIN_RECIEVED = "POST_LOGIN_RECIEVED";
export const POST_REGISTRATION_REQUEST = "POST_REGISTRATION_REQUEST";
export const POST_REGISTRATION_RECEIVED = "POST_REGISTRATION_RECEIVED";
export const EMAIL_VALIDATION = "EMAIL_VALIDATION";
export const SET_TOKEN = "SET_TOKEN";
