export const POST_LOGIN_REQUEST = "POST_LOGIN_REQUEST";
export const POST_LOGIN_RECIEVED = "POST_LOGIN_RECIEVED";
export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_RECEIVED = "REGISTRATION_RECEIVED";
export const EMAIL_VALIDATION = "EMAIL_VALIDATION";
