export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RECIEVED = "LOGIN_RECIEVED";
export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_RECEIVED = "REGISTRATION_RECEIVED";
