export const SET_SCORE_CREATE_MODAL = "SET_SCORE_CREATE_MODAL";
export const HIDE_SCORE_CREATE_MODAL = "HIDE_SCORE_CREATE_MODAL";
export const IS_NOT_EMAIL_IN_SIGN_UP = "IS_NOT_EMAIL_IN_SIGN_UP";
export const IS_EMAIL_IN_SIGN_UP = "IS_EMAIL_IN_SIGN_UP";
