# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "spolyzer.xcodeproj")
    build_app(scheme: "spolyzer(release)")
    upload_to_app_store
  end
    lane :beta do
      get_provisioning_profile
      get_certificates   
    sync_code_signing(type: "appstore",
                      git_url: "git@github.com:Water-Fowl/spolyzer-ios.git",
                      clone_branch_directly: true)
    build_app(scheme: "spolyzer(release)")
    increment_build_number(
      xcodeproj: "spolyzer.xcodeproj",
    )
    upload_to_testflight(scheme: "spolyzer(release)",
      username: "yoshiki.ikeda@water-fowl.co.jp",
      app_identifier: "com.waterfowl.spolyzer",
    )
    slack(message: "Build成功(beta)",
          slack_url: "https://hooks.slack.com/services/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")
  end
end
